### ISSUE TITLE
Fix Server Menu Theme Creation

### ISSUE THREAD

**Issue by IRDeNial** [IRDeNial/BD-Server-Themes#6]
Discord no longer uses the hamburger menu & changed the DOM to access the server menu.  Plugin needs updated to handle this change.

**Comment by tianalemesle** [comment]
up

**Comment by KaKi87** [comment]
up

**Comment by IRDeNial** [comment]
But I'm lazy...

You can always just use the other way of getting the server themes working.  This is a very back-burner thing and isn't needed for the plugin to work.

**Comment by KaKi87** [comment]
If the other way is `{{ServerID}}.servertheme.css`, it's not working for me...

**Comment by IRDeNial** [comment]
@KaKi87 That's a separate issue.  Please create a new issue with the EXACT steps as detailed you're taking as detailed as possible and how to recreate the problem you're running into.

**Comment by IRDeNial** [comment]
This is no longer needed.  Discord no longer uses a menu specific to the server.
Not going to write an event handler for the context menu when it's not necessary.
