### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by exio43** [IRDeNial/BD-Server-Themes#7]
Ive followed the instructions like 5 times in a row and its not working. is there anything im reading wrong in the read me

**Comment by masterw3x** [comment]
Hi!

I don't manage this plugin but my issue was in naming the theme file. Make sure it is named like so:
![image](https://user-images.githubusercontent.com/24599176/30242360-e4f53b54-9549-11e7-8ede-82b26abb0ffb.png)

I think the author of the plugin should be a bit more clear on the file naming 😄

**Comment by IRDeNial** [comment]
> In Discord, right click on the server that you want to create a theme for. Then click "Copy ID". This will give you the server ID.
This will be referred to as {{ServerID}}.
In your themes folder, create a new file and name it {{ServerID}}.servertheme.css

I'm not sure how much more clear I could be.  Follow instructions, and if it's not working, tell me how to reproduce your error.  I can't help you with "It's not working".

**Comment by masterw3x** [comment]
When I first did it, I thought you needed to add the brackets. Maybe include a little tidbit to not include the brackets?
