### ISSUE TITLE
Plugin Doesn't work

### ISSUE THREAD

**Issue by dolciss** [IRDeNial/BD-Server-Themes#9]
Thanks for your plugin.
But it has been no longer work recently...

**Comment by givemhell** [comment]
yeah i seem to have had the same problem today, tried reinstalling betterdiscord and downloading the plugin again but it hasn't even been updated so im guessing a recent update with discord is screwing with it?

**Comment by givemhell** [comment]
it does work however if i pick a server i have setup a theme for and restart discord with ctrl + r

**Comment by UlithiumDragon** [comment]
I can confirm this is an issue. Wish I knew enough CSS to fix this myself, since I really miss this plugin... :/

**Comment by givemhell** [comment]
Sometimes it works just fine. other days i cant get it to load other themes. not sure if its a problem with discord, better discord, or the plugin.

**Comment by IRDeNial** [comment]
@dolciss Works fine for others.  Would you mind sharing your CSS as well as any errors that show up in the console so we can debug this?

@givemhell Can you do the same, but make a new issue.  Don't hijack threads.

**Comment by dolciss** [comment]
I use CSS, ClearVison( https://zerthox.github.io/ClearVision/ ) and customize this.
[ClearVision_Mayu.txt](https://github.com/IRDeNial/BD-Server-Themes/files/1539087/ClearVision_Mayu.txt) , [ClearVision_Miku.txt](https://github.com/IRDeNial/BD-Server-Themes/files/1539088/ClearVision_Miku.txt)

I found this plugin works when server change through direct message.
(ex: ctrl+2(Server1)→ctrl+1(DM)→ctrl+3(Server2))

shown logs
> Injected theme for server xxxxxxxxxxxxxxxxxx

at works plugin, but no shown logs at doesn't work.

i hopes this helps debug...

**Comment by givemhell** [comment]
I also use ClearVison...

I dont see how im hijacking someone else's thread when ive confirmed his problem is the same as mine

The only differnce between me and his problem is i have my own custom code running after clear vision loads however i removed it and tested before i made my comments here...

**Comment by TheDarkBomber** [comment]
How to fix this issue.
Go into the plugin file and replace:
`serverHash = $('.guild.selected a,.guild.active a').attr('href').split('/')[2];`
with
`serverHash = window.location.href.split('/')[4];`
